Is all the socket in ping.raw and the dataxferservice being closed properly even after
exception is being thrown?

check header problem.

does the dataxferrawtester need to have group mamabers name?